title: The Claw
description: A fully autonomous Uber-bot for stuffed animal transportation.
google_analytics: UA-82745005-1
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
